# docker-compose.yml
version: '3.8'

services:
  backend:
    build: 
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    ports:
      - "3000:3000"
    env_file:
      - ./packages/backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker:
    build:
      context: ./packages/worker
      dockerfile: Dockerfile
    container_name: recipe-worker
    env_file:
      - ./packages/worker/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: recipe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend-web:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: recipe-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data: